[MLP-157] Added abstracted data provider, services and models examples
makingsensetraining/mobile-pocs pull request #13
Opened 2017-03-30 20:37 UTC by jsmuguruza

## Background

As we discussed with @mvazquez-ms the idea was to create an example of how to abstract the data providers with their data models and use them in services in a running example. 

It's quite simple, but there are some things on generics that we couldn't make work as we really wanted to with Marce.

## Changes done

1. Modified 2nd storyboard to have a TableView and CustomCell.
2. Created new TableViewController and TableViewCell.
3. Created a Service to consume Data Provider.
4. Created a Data Provider Protocol to abstract it's functionality then implemented it with a simple example.

## Approvers required

@mvazquez-ms @lpelizzaMS @bsztamfater-ms  @mmaldini33 

## Additional Approvers

@AlphaGit  @andresmoschini  @matiasbeckerle  @mravinale

2017-03-31 20:03 UTC, mmaldini33 reviewed
Minimal comment.

2017-03-31 20:03 UTC, mmaldini33 commented on IOS/SwiftSeedProject/SwiftSeedProject/Domain/Services/PersonService.swift
> +    var persons = [Person]()
Type Annotation for Empty Arrays and Dictionaries

For empty arrays and dictionaries, use type annotation. (For an array or dictionary assigned to a large, multi-line literal, use type annotation.)

Preferred:
var names: [Person] = []

Not Preferred:
var persons = [Person]()

2017-04-03 13:33 UTC, mvazquez-ms requested changes

2017-04-03 13:33 UTC, mvazquez-ms commented on IOS/SwiftSeedProject/SwiftSeedProject/Domain/Models/Person.swift
> +    var name: String!
Please, add a blank line between these two.

2017-04-03 13:33 UTC, mvazquez-ms commented on IOS/SwiftSeedProject/SwiftSeedProject/Domain/Services/PersonService.swift
> +    let dataProvider : InMemoryDataProvider
Please, add a blank line between these two.

2017-04-03 13:33 UTC, mvazquez-ms commented on IOS/SwiftSeedProject/SwiftSeedProject/Domain/Services/PersonService.swift
> +    let dataProvider : InMemoryDataProvider
`dataProvider` should be declared as

`let dataProvider : DataProvider`

(As the protocol, not the implementation)

2017-04-03 13:33 UTC, mvazquez-ms commented on IOS/SwiftSeedProject/SwiftSeedProject/Domain/Services/PersonService.swift
> +open class PersonService {
Why is this class `open`?

2017-04-03 13:33 UTC, mvazquez-ms commented on IOS/SwiftSeedProject/SwiftSeedProject/Domain/Services/PersonService.swift
> +    init() {
Usually, the constructor should set dependencies and initial configuration, but nothing else.

The query to the DataProvider should be done separately, on a specific method or changing persons property to be lazy.

2017-04-03 13:33 UTC, mvazquez-ms commented on IOS/SwiftSeedProject/SwiftSeedProject/Domain/Services/PersonService.swift
> +    var persons = [Person]()
This array should be declared as `let`.

Even if you modify it, you'll (and should) modify only the content, not the array itself (e.g. recreating it)

2017-04-03 13:33 UTC, mvazquez-ms commented on IOS/SwiftSeedProject/SwiftSeedProject/Domain/Services/PersonService.swift
> +        let result : [AnyObject] = dataProvider.getEntities()
`result` name is waaaaaaaaaaaaay too generic.

Name should be something like `personEntities` or similar.

2017-04-03 13:33 UTC, mvazquez-ms commented on IOS/SwiftSeedProject/SwiftSeedProject/Domain/Services/PersonService.swift
> +        let result : [AnyObject] = dataProvider.getEntities()
`let result : [AnyObject] = dataProvider.getEntities()`

This is not taking advantage of generics usage, it should be written as

`let result : [PersonDataModel] = dataProvider.getEntities()`

2017-04-03 13:33 UTC, mvazquez-ms commented on IOS/SwiftSeedProject/SwiftSeedProject/Domain/Services/PersonService.swift
> +        for object in result {
Both, `object` and `result` are painfully generic names.

2017-04-03 13:33 UTC, mvazquez-ms commented on IOS/SwiftSeedProject/SwiftSeedProject/Domain/Services/PersonService.swift
> +            let person = Person(dataModel: object as! PersonDataModel)
Casting here could (and should) be avoided if the change suggested on [this ](https://github.com/makingsensetraining/mobile-pocs/pull/13/files#r109415104)comment is implemented.

2017-04-03 13:33 UTC, mvazquez-ms commented on IOS/SwiftSeedProject/SwiftSeedProject/Infrastructure/Persistence/Implementations/InMemoryDataProvider.swift
> +    let entities : [AnyObject] = [
Please, add a blank line between these two.

2017-04-03 13:33 UTC, mvazquez-ms commented on IOS/SwiftSeedProject/SwiftSeedProject/Infrastructure/Persistence/Implementations/InMemoryDataProvider.swift
> +        return result as! [T]
What happen with this forced casting if result is empty?

2017-04-03 13:33 UTC, mvazquez-ms commented on IOS/SwiftSeedProject/SwiftSeedProject/Infrastructure/Persistence/Implementations/InMemoryDataProvider.swift
> +class InMemoryDataProvider  {
Extra spacing before curly brace.

2017-04-03 13:33 UTC, mvazquez-ms commented on IOS/SwiftSeedProject/SwiftSeedProject/Infrastructure/Persistence/Models/PersonDataModel.swift
> +    let name: String
Please, add a blank line between these two.

2017-04-03 13:33 UTC, mvazquez-ms commented on IOS/SwiftSeedProject/SwiftSeedProject/Interfaces/ViewControllers/Person/PersonTableViewCell.swift
> +    @IBOutlet weak var lblName: UILabel!
Please, add a blank line between these two.

2017-04-03 13:33 UTC, mvazquez-ms commented on IOS/SwiftSeedProject/SwiftSeedProject/Interfaces/ViewControllers/Person/PersonTableViewCell.swift
> +    override func awakeFromNib() {
Please, remove useless code.

2017-04-03 13:33 UTC, mvazquez-ms commented on IOS/SwiftSeedProject/SwiftSeedProject/Interfaces/ViewControllers/PersonTableViewController.swift
> +    @IBOutlet weak var tblView: UITableView!
Please, add a blank line between these two.

2017-04-03 13:33 UTC, mvazquez-ms commented on IOS/SwiftSeedProject/SwiftSeedProject/Interfaces/ViewControllers/PersonTableViewController.swift
> +        cell.lblName.text = service?.persons[indexPath.row].name
This line should be handled by the cell class. This view controller can't be responsible of configuring cell's inner views.

2017-04-03 18:16 UTC, briansztamfater requested changes

2017-04-03 18:16 UTC, bsztamfater-ms commented on IOS/SwiftSeedProject/SwiftSeedProject/Domain/Models/Person.swift
> +class Person : NSObject {
I think models should not extend NSObject, unless is necessary

2017-04-21 10:49 UTC, closed without merging